/*
 * This file was automatically generated by thebigsasha's Sanity Codegen. (http://thebigsasha.github.io/sanity_config_creator/)
 * Read more at the link above.
 */
import { defineField, defineType } from 'sanity'

export default defineType({
  type: 'document',
  name: 'TagDetails',
  title: 'Tag Details',
  description: 'Details to render alongside a tag',
  fields: [
    defineField({
      type: 'string',
      name: 'tag',
      title: 'Tag',
      description: 'The tag being detailed',
    }),
    defineField({
      type: 'string',
      name: 'title',
      title: 'Title',
      description: 'The title to render',
    }),
    defineField({
      type: 'array',
      name: 'overview',
      title: 'Overview',
      description: 'The description of the tag',
      of: [{ type: 'block' }],
      options: {
        layout: 'grid',
      },
    }),
  ],
})
